"""Add unique constraint (portfolio_id, isin) and currency column

Revision ID: edf3035192be
Revises: 
Create Date: 2025-10-25 08:25:54.694262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf3035192be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_portfolio_isin', ['portfolio_id', 'isin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_constraint('uix_portfolio_isin', type_='unique')

    # ### end Alembic commands ###
